plugins {
    id 'java'
    id 'net.neoforged.moddev' version '2.0.144'
}

group = 'dev.eynoik'
version = '0.1.7'

base {
    archivesName = 'asyncsablefix'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = '21.1.248'
    mods {
        asyncsablefix {
            sourceSet sourceSets.main
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
